CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    whatsapp_number TEXT,
    last_login_at TIMESTAMP,
    whatsapp_onboarding_sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS properties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_username TEXT,
    tenant_name TEXT NOT NULL,
    property_name TEXT,
    rent_amount DOUBLE PRECISION NOT NULL,
    rent_due_day INTEGER,
    lease_start DATE,
    lease_end DATE,
    phone_number TEXT,
    unit_number TEXT,
    property_address TEXT,
    security_deposit DOUBLE PRECISION,
    lease_terms TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    last_paid_date DATE,
    last_payment_amount DOUBLE PRECISION,
    current_month_paid_amount DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unmatched_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_username TEXT,
    raw_message TEXT NOT NULL,
    extracted_tenant_name TEXT,
    sender_key TEXT,
    amount DOUBLE PRECISION NOT NULL,
    payment_date DATE NOT NULL,
    candidates_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'UNMATCHED',
    matched_property_id INTEGER,
    matched_payment_id INTEGER,
    resolution_note TEXT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_aliases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    sender_key TEXT NOT NULL UNIQUE,
    sender_name TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS whatsapp_pending_matches (
    wa_id TEXT PRIMARY KEY,
    original_message TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    payment_date DATE NOT NULL,
    sender_key TEXT,
    sender_name TEXT,
    unmatched_payment_id INTEGER,
    candidates_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rent_increases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    date_from DATE NOT NULL,
    date_till DATE NOT NULL,
    rent_amount DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INTEGER NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    amount DOUBLE PRECISION NOT NULL,
    payment_date DATE NOT NULL,
    source TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'POSTED',
    sender_key TEXT,
    raw_message TEXT,
    unmatched_payment_id INTEGER,
    note TEXT,
    reversal_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payments_property_date ON payments(property_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_unmatched_status ON unmatched_payments(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username);
